### PR TITLE
Updating solver paramaters at each iteration

### PR DESCRIPTION
**Pull request by junglegobs**
Addresses issue https://github.com/NREL/ProgressiveHedging.jl/issues/14

I haven't done much or tested, but just for the sake of organising my thoughts here's what I've done:

1. At each iteration, `solve_subproblems` is called in `algorithm.jl`.
2. Here, before solving the subproblem, the function `_update_solver_parameters` is called.
3. `_update_solver_parameters` (defined in `algorithm.jl`) sends a `UpdateSolverParameters` message with the PH iteration number to the workers.
4. In `worker.jl`, `process_message` is defined for `UpdateSolverParameters`. This calls `update_solver_parameters` with the subproblem and iteration number as parameters.
5. The user has to `PH.update_solver_parameters(js, iter)` to get this functionality. Unless specified by the user, `update_solver_parameters` does nothing.

### CODE REVIEW

**Comment by junglegobs** [comment]
I've just realised that this is needlessly complicated. There doesn't need to be any communication between the master and sub problem for this (although it might be a bit more transparent if there is). @jmaack24 what do you think? I've realised that I probably need this in order to solve my problem, so I will start working on it again.

**Comment by junglegobs** [comment]
@jmaack24 I just saw that you added user defined callbacks. I suppose it makes more sense to simply use this than to implement it into the package?

**Comment by jmaack24** [comment]
> @jmaack24 I just saw that you added user defined callbacks. I suppose it makes more sense to simply use this than to implement it into the package?

You can use the callbacks to update the solver parameters. There's a more efficient way to implement this though that is handled completely by the worker process right before `solve` is called on each subproblem.  If you're looking to solve a problem with a lot of scenarios, the time savings may be significant.

I'll let you decide if you still want to implement this or not.  It is a good feature.

**Comment by junglegobs** [comment]
I prefer the more generalisable callbacks that you implemented. Your point about efficiency made me think that it could be possible / desirable to add "WorkerCallbacks" - callbacks that can be implemented at the worker level without interaction with the "Master" worker (not sure what the best definition of that would be).

**Comment by jmaack24** [comment]
> it could be possible / desirable to add "WorkerCallbacks" - callbacks that can be implemented at the worker level without interaction with the "Master"

That was my thought on implementing the optimizer parameter updates was to add callbacks for the subproblems. I'd name them `SubproblemCallback` with the idea that a user may want to apply a callback to a subset of subproblems. Definitely something that could be useful.

Do you have the time and are you interested in implementing it?

**Comment by junglegobs** [comment]
I would be interested (I quite enjoy working on well thought out code), time wise I have to balance a fair few jobs so it would probably take 2-3 weeks. Is that ok?

Implementation wise, I assume there would be a need for an additional message to all the workers to assign them their `SubproblemCallback` functions right? (I ask because I imagine that would probably be the most complicated part).

**Comment by jmaack24** [comment]
> it would probably take 2-3 weeks. Is that ok?

That's fine.

> Implementation wise, I assume there would be a need for an additional message to all the workers to assign them their `SubproblemCallback` functions right? (I ask because I imagine that would probably be the most complicated part).

I would actually just add a field to the `Initialize` message and have the workers save the callbacks for each subproblem from there.

**Pull request closed without merging**
